[package]
name = "bwadvent"
version = "0.1.0"
authors = ["Dabo Ross <daboross@daboross.net>"]

[lib]
name = "bwadvent"
path = "src/rust/lib.rs"

[dependencies]
nom = "0.4"
time = "0.1"
piston = "0.10"
piston2d-graphics = "0.9"
pistoncore-glutin_window = "0.12"
piston2d-opengl_graphics = "0.12"
collisions = { path = "../collisions/" }
image = { version = "0.3", default-features = false, features = ["png"] }
