[package]
name = "bwadvent"
version = "0.1.0"
authors = ["Dabo Ross <daboross@daboross.net>"]

[lib]
name = "bwadvent"
path = "src/rust/lib.rs"

[dependencies]
nom = "1.0"
time = "0.1"
piston = "0.16"
piston2d-graphics = "0.13"
pistoncore-glutin_window = "0.20"
piston2d-opengl_graphics = "0.22"
collisions = { git = "https://github.com/daboross/rust-temp-collisions.git" }
image = { version = "0.6", default-features = false, features = ["png"] }
