[package]
name = "bwadvent"
version = "0.1.0"
authors = ["Dabo Ross <daboross@daboross.net>"]

[lib]
name = "bwadvent"
path = "src/rust/lib.rs"

[dependencies]
nom = "1.2.1"
time = "0.1"
piston = "0.17"
piston_window ="0.34.0"
piston2d-graphics = "0.13"
piston2d-opengl_graphics = "0.23"
collisions = { git = "https://github.com/daboross/rust-temp-collisions.git" }
image = { version = "0.6", default-features = false, features = ["png"] }
