[package]
name = "bwadvent"
version = "0.0.1"
authors = ["Dabo Ross <daboross@daboross.net>"]

[lib]
name = "bwadvent"
path = "src/rust/lib.rs"

[dependencies]
nom = "1.2"
time = "0.1"
piston = "0.22"
piston_window = "0.47"
pistoncore-sdl2_window = "0.30"
piston2d-graphics = "0.16"
piston2d-opengl_graphics = "0.29"
collisions = { git = "https://github.com/daboross/rust-temp-collisions.git" }
image = { version = "0.10", default-features = false, features = ["png"] }
